# Generated by Django 5.2.4 on 2025-08-10 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("u_num", models.CharField(max_length=20, verbose_name="提交标号")),
                (
                    "s_num",
                    models.CharField(max_length=20, null=True, verbose_name="学生学号"),
                ),
                (
                    "h_num",
                    models.CharField(max_length=20, null=True, verbose_name="题目序号"),
                ),
                ("up_time", models.DateTimeField(null=True, verbose_name="提交时间")),
                (
                    "up_fname",
                    models.CharField(max_length=255, null=True, verbose_name="文件名"),
                ),
                ("up_path", models.TextField(null=True, verbose_name="提交文件路径")),
                (
                    "createtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updatetime",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "open_time",
                    models.DateTimeField(null=True, verbose_name="交互开启时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(null=True, verbose_name="交互结束时间"),
                ),
                (
                    "star",
                    models.CharField(max_length=5, null=True, verbose_name="关卡评分"),
                ),
                (
                    "answer_open",
                    models.IntegerField(
                        choices=[(0, "未查看参考答案"), (1, "已查看参考答案")],
                        default=0,
                        verbose_name="是否查看参考答案",
                    ),
                ),
                (
                    "evaluate_count",
                    models.CharField(
                        default="0", max_length=5, verbose_name="用户评测次数"
                    ),
                ),
                (
                    "score",
                    models.CharField(max_length=5, null=True, verbose_name="分数"),
                ),
                ("advice", models.TextField(null=True, verbose_name="修改建议")),
                (
                    "ressuggest",
                    models.TextField(null=True, verbose_name="资源推荐理由"),
                ),
                (
                    "knowledgegraph",
                    models.CharField(
                        max_length=64, null=True, verbose_name="知识点知识图谱"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "未通过该关卡"),
                            (1, "用户提交结果正在评测"),
                            (2, "用户通过该关卡"),
                            (3, "用户未开启本关卡"),
                        ],
                        default=0,
                        verbose_name="评测状态",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        default="未提交", max_length=5, verbose_name="提交状态"
                    ),
                ),
            ],
            options={
                "verbose_name": "题目文档提交",
                "verbose_name_plural": "题目文档提交",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("s_num", models.CharField(max_length=20, unique=True)),
                (
                    "name",
                    models.CharField(max_length=20, null=True, verbose_name="学生姓名"),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=20, null=True, verbose_name="学生用户名"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        default="123456", max_length=128, verbose_name="密码"
                    ),
                ),
                (
                    "class_num",
                    models.CharField(
                        max_length=64, null=True, verbose_name="学生班级号"
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, null=True, verbose_name="学生手机"),
                ),
                (
                    "email",
                    models.CharField(max_length=64, null=True, verbose_name="学生邮箱"),
                ),
                ("jwt", models.TextField(null=True, verbose_name="验证令牌")),
                (
                    "createtime",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "学生",
                "verbose_name_plural": "学生",
            },
        ),
    ]
