# Generated by Django 5.2.4 on 2025-07-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "s_num",
                    models.CharField(
                        default="6135cef3", max_length=20, verbose_name="学生学号"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, null=True, verbose_name="学生姓名"),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=20, null=True, verbose_name="学生用户名"
                    ),
                ),
                (
                    "password",
                    models.CharField(max_length=20, null=True, verbose_name="学生密码"),
                ),
                (
                    "class_name",
                    models.CharField(max_length=20, null=True, verbose_name="学生班级"),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, null=True, verbose_name="学生手机"),
                ),
                (
                    "email",
                    models.CharField(max_length=20, null=True, verbose_name="学生邮箱"),
                ),
                (
                    "jwt",
                    models.CharField(
                        max_length=255, null=True, verbose_name="验证令牌"
                    ),
                ),
                (
                    "createtime",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
            ],
            options={
                "verbose_name": "学生",
                "verbose_name_plural": "学生",
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "u_num",
                    models.CharField(
                        default="f06b84a7", max_length=20, verbose_name="提交标号"
                    ),
                ),
                (
                    "s_num",
                    models.CharField(max_length=20, null=True, verbose_name="学生学号"),
                ),
                (
                    "h_num",
                    models.CharField(max_length=20, null=True, verbose_name="题目序号"),
                ),
                ("up_time", models.DateTimeField(null=True, verbose_name="提交时间")),
                (
                    "score",
                    models.CharField(max_length=5, null=True, verbose_name="分数"),
                ),
                ("advice", models.TextField(null=True, verbose_name="修改建议")),
                (
                    "ressuggest",
                    models.TextField(null=True, verbose_name="资源推荐理由"),
                ),
                (
                    "knowledgegraph",
                    models.CharField(
                        max_length=64, null=True, verbose_name="知识点知识图谱"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="未提交", max_length=5, verbose_name="提交状态"
                    ),
                ),
            ],
            options={
                "verbose_name": "题目文档提交",
                "verbose_name_plural": "题目文档提交",
            },
        ),
    ]
