# Generated by Django 5.2.4 on 2025-07-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="s_num",
            field=models.CharField(
                default="91fc69d4", max_length=20, verbose_name="学生学号"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="u_num",
            field=models.CharField(
                default="2ec878e2", max_length=20, verbose_name="提交标号"
            ),
        ),
    ]
