# Generated by Django 5.2.4 on 2025-07-28 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="class_name",
        ),
        migrations.AddField(
            model_name="student",
            name="class_num",
            field=models.CharField(max_length=64, null=True, verbose_name="学生班级号"),
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="answer_open",
            field=models.IntegerField(
                choices=[(0, "未查看参考答案"), (1, "已查看参考答案")],
                default=0,
                verbose_name="是否查看参考答案",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="condition",
            field=models.CharField(
                default="未提交", max_length=5, verbose_name="提交状态"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="createtime",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="创建时间"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="end_time",
            field=models.DateTimeField(null=True, verbose_name="交互结束时间"),
        ),
        migrations.AddField(
            model_name="submission",
            name="evaluate_count",
            field=models.CharField(
                default="0", max_length=5, verbose_name="用户评测次数"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="open_time",
            field=models.DateTimeField(null=True, verbose_name="交互开启时间"),
        ),
        migrations.AddField(
            model_name="submission",
            name="star",
            field=models.CharField(max_length=5, null=True, verbose_name="关卡评分"),
        ),
        migrations.AddField(
            model_name="submission",
            name="up_fname",
            field=models.CharField(max_length=255, null=True, verbose_name="文件名"),
        ),
        migrations.AddField(
            model_name="submission",
            name="up_path",
            field=models.TextField(null=True, verbose_name="提交文件路径"),
        ),
        migrations.AddField(
            model_name="submission",
            name="updatetime",
            field=models.DateTimeField(auto_now=True, verbose_name="修改时间"),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.CharField(max_length=64, null=True, verbose_name="学生邮箱"),
        ),
        migrations.AlterField(
            model_name="student",
            name="jwt",
            field=models.TextField(null=True, verbose_name="验证令牌"),
        ),
        migrations.AlterField(
            model_name="student",
            name="password",
            field=models.CharField(
                default="123456", max_length=128, verbose_name="密码"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="s_num",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "未通过该关卡"),
                    (1, "用户提交结果正在评测"),
                    (2, "用户通过该关卡"),
                    (3, "用户未开启本关卡"),
                ],
                default=0,
                verbose_name="评测状态",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="u_num",
            field=models.CharField(max_length=20, verbose_name="提交标号"),
        ),
    ]
