# Generated by Django 5.2.4 on 2025-08-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="up_fname",
            field=models.CharField(
                default="", max_length=255, null=True, verbose_name="文件名"
            ),
        ),
    ]
