# Generated by Django 5.2.4 on 2025-07-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_student_s_num_alter_submission_u_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="s_num",
            field=models.CharField(
                default="3b72fee8", max_length=20, verbose_name="学生学号"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="u_num",
            field=models.CharField(
                default="9bde9920", max_length=20, verbose_name="提交标号"
            ),
        ),
    ]
