# Generated by Django 5.2.4 on 2025-07-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_student_s_num_alter_submission_u_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="password",
            field=models.CharField(
                default="123456", max_length=128, verbose_name="密码"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="s_num",
            field=models.CharField(
                default="4c313729", max_length=20, verbose_name="学生学号"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="u_num",
            field=models.CharField(
                default="d1c24634", max_length=20, verbose_name="提交标号"
            ),
        ),
    ]
