# Generated by Django 5.2.4 on 2025-07-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_alter_student_password_alter_student_s_num_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="class_name",
            field=models.CharField(max_length=64, null=True, verbose_name="学生班级"),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.CharField(max_length=64, null=True, verbose_name="学生邮箱"),
        ),
        migrations.AlterField(
            model_name="student",
            name="s_num",
            field=models.CharField(
                default="8dda2698", max_length=20, verbose_name="学生学号"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="u_num",
            field=models.CharField(
                default="ef362a1c", max_length=20, verbose_name="提交标号"
            ),
        ),
    ]
