# Generated by Django 5.2.4 on 2025-07-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_alter_student_class_name_alter_student_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="s_num",
            field=models.CharField(max_length=20, verbose_name="学生学号"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="u_num",
            field=models.CharField(
                default="8d2b169f", max_length=20, verbose_name="提交标号"
            ),
        ),
    ]
