# Generated by Django 5.2.4 on 2025-07-23 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_alter_student_s_num_alter_submission_u_num"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="s_num",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="u_num",
            field=models.CharField(
                default="b8731f4b", max_length=20, verbose_name="提交标号"
            ),
        ),
    ]
