# Generated by Django 5.2.4 on 2025-07-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_student_user_alter_student_s_num_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="u_num",
            field=models.CharField(
                default="b1dd3fc5", max_length=20, verbose_name="提交标号"
            ),
        ),
    ]
