# Generated by Django 5.2.4 on 2025-07-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0008_alter_submission_u_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="jwt",
            field=models.TextField(null=True, verbose_name="验证令牌"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="u_num",
            field=models.CharField(
                default="0cd89313", max_length=20, verbose_name="提交标号"
            ),
        ),
    ]
