# Generated by Django 5.2.4 on 2025-07-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_alter_student_jwt_alter_submission_u_num"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="class_name",
        ),
        migrations.AddField(
            model_name="student",
            name="class_num",
            field=models.CharField(max_length=64, null=True, verbose_name="学生班级号"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="u_num",
            field=models.CharField(
                default="55d1db0b", max_length=20, verbose_name="提交标号"
            ),
        ),
    ]
