# Generated by Django 5.2.4 on 2025-07-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0010_remove_student_class_name_student_class_num_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="u_num",
            field=models.CharField(
                default="807ca60e", max_length=20, verbose_name="提交标号"
            ),
        ),
    ]
