# Generated by Django 5.2.4 on 2025-07-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0012_alter_submission_u_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="u_num",
            field=models.CharField(
                default="d9ec5c4e", max_length=20, verbose_name="提交标号"
            ),
        ),
    ]
