# Generated by Django 5.2.4 on 2025-07-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "c_num",
                    models.CharField(
                        default="af11ceb4", max_length=20, verbose_name="班级号"
                    ),
                ),
                (
                    "c_name",
                    models.CharField(max_length=20, null=True, verbose_name="班级名"),
                ),
                (
                    "t_num",
                    models.CharField(max_length=20, null=True, verbose_name="教师工号"),
                ),
                (
                    "grade",
                    models.CharField(max_length=20, null=True, verbose_name="所属年级"),
                ),
                (
                    "number",
                    models.IntegerField(
                        max_length=10, null=True, verbose_name="班级人数"
                    ),
                ),
                (
                    "createtime",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
                (
                    "updatetime",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
            ],
            options={
                "verbose_name": "班级",
                "verbose_name_plural": "班级",
                "ordering": ["c_name"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "l_num",
                    models.CharField(
                        default="71d541fd", max_length=20, verbose_name="课程号"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=20, null=True, verbose_name="课程名"),
                ),
                (
                    "t_num",
                    models.CharField(max_length=20, null=True, verbose_name="教师工号"),
                ),
                ("des", models.TextField(null=True, verbose_name="课程描述")),
                (
                    "type",
                    models.CharField(max_length=64, null=True, verbose_name="课程类型"),
                ),
                (
                    "credit",
                    models.IntegerField(
                        max_length=4, null=True, verbose_name="课程学分"
                    ),
                ),
                (
                    "createtime",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
                (
                    "updatetime",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "课程",
            },
        ),
        migrations.CreateModel(
            name="CourseResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "r_num",
                    models.CharField(
                        default="a1113eaa", max_length=20, verbose_name="资源序号"
                    ),
                ),
                (
                    "l_num",
                    models.CharField(max_length=20, null=True, verbose_name="课程号"),
                ),
                (
                    "r_name",
                    models.CharField(max_length=64, null=True, verbose_name="文件名"),
                ),
                (
                    "r_path",
                    models.CharField(
                        max_length=255, null=True, verbose_name="文件存储路径"
                    ),
                ),
                (
                    "r_type",
                    models.CharField(max_length=20, null=True, verbose_name="文件类型"),
                ),
                (
                    "createtime",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
            ],
            options={
                "verbose_name": "课程资源",
                "verbose_name_plural": "课程资源",
            },
        ),
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "h_num",
                    models.CharField(
                        default="6f8fd2f8", max_length=20, verbose_name="作业号"
                    ),
                ),
                (
                    "l_num",
                    models.CharField(max_length=20, null=True, verbose_name="课程号"),
                ),
                (
                    "title",
                    models.CharField(max_length=20, null=True, verbose_name="作业标题"),
                ),
                ("des", models.TextField(null=True, verbose_name="作业详细说明")),
                (
                    "hd_name",
                    models.CharField(
                        max_length=64, null=True, verbose_name="作业文件名"
                    ),
                ),
                (
                    "hd_path",
                    models.CharField(
                        max_length=255, null=True, verbose_name="作业文件存储路径"
                    ),
                ),
                (
                    "hd_type",
                    models.CharField(max_length=20, null=True, verbose_name="文件类型"),
                ),
                (
                    "createtime",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
                (
                    "updatetime",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
            ],
            options={
                "verbose_name": "作业",
                "verbose_name_plural": "作业",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "t_num",
                    models.CharField(
                        default="f6767d1a", max_length=20, verbose_name="老师工号"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, null=True, verbose_name="老师姓名"),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=20, null=True, verbose_name="老师用户名"
                    ),
                ),
                (
                    "password",
                    models.CharField(max_length=20, null=True, verbose_name="老师密码"),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, null=True, verbose_name="老师手机"),
                ),
                (
                    "email",
                    models.CharField(max_length=20, null=True, verbose_name="老师邮箱"),
                ),
                (
                    "jwt",
                    models.CharField(
                        max_length=255, null=True, verbose_name="验证令牌"
                    ),
                ),
                (
                    "createtime",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
            ],
            options={
                "verbose_name": "教师",
                "verbose_name_plural": "教师",
            },
        ),
        migrations.CreateModel(
            name="CourseEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "o_num",
                    models.CharField(
                        default="38048224", max_length=20, verbose_name="选修号"
                    ),
                ),
                (
                    "c_num",
                    models.CharField(max_length=20, null=True, verbose_name="班级号"),
                ),
                (
                    "l_num",
                    models.CharField(max_length=20, null=True, verbose_name="课程号"),
                ),
                (
                    "createtime",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
            ],
            options={
                "verbose_name": "班级课程选修",
                "verbose_name_plural": "班级课程选修",
                "unique_together": {("c_num", "l_num")},
            },
        ),
    ]
