# Generated by Django 5.2.4 on 2025-07-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="c_num",
            field=models.CharField(
                default="1e4b9da3", max_length=20, verbose_name="班级号"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="credit",
            field=models.IntegerField(null=True, verbose_name="课程学分"),
        ),
        migrations.AlterField(
            model_name="course",
            name="l_num",
            field=models.CharField(
                default="d58bdc5b", max_length=20, verbose_name="课程号"
            ),
        ),
        migrations.AlterField(
            model_name="courseenrollment",
            name="o_num",
            field=models.CharField(
                default="4ad42b70", max_length=20, verbose_name="选修号"
            ),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="r_num",
            field=models.CharField(
                default="8c4287e7", max_length=20, verbose_name="资源序号"
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="h_num",
            field=models.CharField(
                default="4f6eff5c", max_length=20, verbose_name="作业号"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="t_num",
            field=models.CharField(
                default="8f4b17b4", max_length=20, verbose_name="老师工号"
            ),
        ),
    ]
