# Generated by Django 5.2.4 on 2025-07-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0002_alter_class_c_num_alter_course_credit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="c_num",
            field=models.CharField(
                default="192b8219", max_length=20, verbose_name="班级号"
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="number",
            field=models.IntegerField(null=True, verbose_name="班级人数"),
        ),
        migrations.AlterField(
            model_name="course",
            name="l_num",
            field=models.CharField(
                default="d5cce8a9", max_length=20, verbose_name="课程号"
            ),
        ),
        migrations.AlterField(
            model_name="courseenrollment",
            name="o_num",
            field=models.CharField(
                default="47049a56", max_length=20, verbose_name="选修号"
            ),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="r_num",
            field=models.CharField(
                default="70a9b70c", max_length=20, verbose_name="资源序号"
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="h_num",
            field=models.CharField(
                default="e9e9cb2d", max_length=20, verbose_name="作业号"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="t_num",
            field=models.CharField(
                default="5b0eb336", max_length=20, verbose_name="老师工号"
            ),
        ),
    ]
