# Generated by Django 5.2.4 on 2025-07-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0003_alter_class_c_num_alter_class_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="c_num",
            field=models.CharField(
                default="a610bba3", max_length=20, verbose_name="班级号"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="l_num",
            field=models.CharField(
                default="98888812", max_length=20, verbose_name="课程号"
            ),
        ),
        migrations.AlterField(
            model_name="courseenrollment",
            name="o_num",
            field=models.CharField(
                default="833921a3", max_length=20, verbose_name="选修号"
            ),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="r_num",
            field=models.CharField(
                default="386cd788", max_length=20, verbose_name="资源序号"
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="h_num",
            field=models.CharField(
                default="1ed8eea5", max_length=20, verbose_name="作业号"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="password",
            field=models.CharField(
                default="123456", max_length=128, verbose_name="密码"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="t_num",
            field=models.CharField(
                default="cbc342b7", max_length=20, verbose_name="老师工号"
            ),
        ),
    ]
