# Generated by Django 5.2.4 on 2025-07-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0004_alter_class_c_num_alter_course_l_num_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="c_num",
            field=models.CharField(
                default="5aba73b6", max_length=20, verbose_name="班级号"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="l_num",
            field=models.CharField(
                default="80d476f7", max_length=20, verbose_name="课程号"
            ),
        ),
        migrations.AlterField(
            model_name="courseenrollment",
            name="o_num",
            field=models.CharField(
                default="2044c8a8", max_length=20, verbose_name="选修号"
            ),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="r_num",
            field=models.CharField(
                default="7654e7f7", max_length=20, verbose_name="资源序号"
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="h_num",
            field=models.CharField(
                default="61ea90bc", max_length=20, verbose_name="作业号"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="email",
            field=models.CharField(max_length=64, null=True, verbose_name="老师邮箱"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="t_num",
            field=models.CharField(
                default="7f1f52fb", max_length=20, verbose_name="老师工号"
            ),
        ),
    ]
