# Generated by Django 5.2.4 on 2025-07-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0007_alter_class_c_num_alter_course_l_num_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="c_num",
            field=models.CharField(
                default="e9693dd1", max_length=20, verbose_name="班级号"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="l_num",
            field=models.CharField(
                default="aad40d47", max_length=20, verbose_name="课程号"
            ),
        ),
        migrations.AlterField(
            model_name="courseenrollment",
            name="o_num",
            field=models.CharField(
                default="041ee2ca", max_length=20, verbose_name="选修号"
            ),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="r_num",
            field=models.CharField(
                default="77b95b9a", max_length=20, verbose_name="资源序号"
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="h_num",
            field=models.CharField(
                default="df8e7200", max_length=20, verbose_name="作业号"
            ),
        ),
    ]
