# Generated by Django 5.2.4 on 2025-07-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0011_teacher_user_alter_class_c_num_alter_course_l_num_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="c_num",
            field=models.CharField(
                default="570e0a1d", max_length=20, verbose_name="班级号"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="l_num",
            field=models.CharField(
                default="9af6fc1e", max_length=20, verbose_name="课程号"
            ),
        ),
        migrations.AlterField(
            model_name="courseenrollment",
            name="o_num",
            field=models.CharField(
                default="b68cddae", max_length=20, verbose_name="选修号"
            ),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="r_num",
            field=models.CharField(
                default="fd421051", max_length=20, verbose_name="资源序号"
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="h_num",
            field=models.CharField(
                default="75679ffc", max_length=20, verbose_name="作业号"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="jwt",
            field=models.TextField(null=True, verbose_name="验证令牌"),
        ),
    ]
