# Generated by Django 5.2.4 on 2025-07-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0012_alter_class_c_num_alter_course_l_num_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="c_num",
            field=models.CharField(max_length=20, verbose_name="班级号"),
        ),
        migrations.AlterField(
            model_name="course",
            name="l_num",
            field=models.CharField(
                default="d03da898", max_length=20, verbose_name="课程号"
            ),
        ),
        migrations.AlterField(
            model_name="courseenrollment",
            name="o_num",
            field=models.CharField(
                default="17562114", max_length=20, verbose_name="选修号"
            ),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="r_num",
            field=models.CharField(
                default="9ffff6d8", max_length=20, verbose_name="资源序号"
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="h_num",
            field=models.CharField(
                default="345392db", max_length=20, verbose_name="作业号"
            ),
        ),
    ]
