# Generated by Django 5.2.4 on 2025-07-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0013_alter_class_c_num_alter_course_l_num_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="l_num",
            field=models.CharField(
                default="a9df87f0", max_length=20, verbose_name="课程号"
            ),
        ),
        migrations.AlterField(
            model_name="courseenrollment",
            name="o_num",
            field=models.CharField(
                default="019f179f", max_length=20, verbose_name="选修号"
            ),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="r_num",
            field=models.CharField(
                default="a3f3368b", max_length=20, verbose_name="资源序号"
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="h_num",
            field=models.CharField(
                default="d8e20615", max_length=20, verbose_name="作业号"
            ),
        ),
    ]
