# Generated by Django 5.2.4 on 2025-07-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0014_alter_course_l_num_alter_courseenrollment_o_num_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="l_num",
            field=models.CharField(max_length=20, verbose_name="课程号"),
        ),
        migrations.AlterField(
            model_name="courseenrollment",
            name="o_num",
            field=models.CharField(max_length=20, verbose_name="选修号"),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="r_num",
            field=models.CharField(
                default="49140e72", max_length=20, verbose_name="资源序号"
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="h_num",
            field=models.CharField(
                default="1ae92dce", max_length=20, verbose_name="作业号"
            ),
        ),
    ]
