# Generated by Django 5.2.4 on 2025-07-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0015_alter_course_l_num_alter_courseenrollment_o_num_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseresource",
            name="r_num",
            field=models.CharField(
                default="76d6386f", max_length=20, verbose_name="资源序号"
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="h_num",
            field=models.CharField(
                default="59f42129", max_length=20, verbose_name="作业号"
            ),
        ),
    ]
