# Generated by Django 5.2.4 on 2025-07-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0018_alter_courseresource_r_num_alter_homework_h_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseresource",
            name="r_num",
            field=models.CharField(
                default="fdea5edc", max_length=20, verbose_name="资源序号"
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="h_num",
            field=models.CharField(max_length=20, verbose_name="作业号"),
        ),
    ]
