# Generated by Django 5.2.4 on 2025-07-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0019_alter_courseresource_r_num_alter_homework_h_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseresource",
            name="r_num",
            field=models.CharField(
                default="ddb0407f", max_length=20, verbose_name="资源序号"
            ),
        ),
    ]
