# Generated by Django 5.2.4 on 2025-07-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0031_alter_courseresource_r_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseresource",
            name="r_num",
            field=models.CharField(
                default="e93a16a9", max_length=20, verbose_name="资源序号"
            ),
        ),
    ]
