# Generated by Django 5.2.4 on 2025-07-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0033_alter_courseresource_r_num"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseresource",
            name="r_name",
        ),
        migrations.AddField(
            model_name="courseresource",
            name="r_des",
            field=models.TextField(null=True, verbose_name="课课程资源简介"),
        ),
        migrations.AddField(
            model_name="courseresource",
            name="r_title",
            field=models.TextField(null=True, verbose_name="课程资源标题"),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="r_num",
            field=models.CharField(
                default="31a08fac", max_length=20, verbose_name="资源序号"
            ),
        ),
    ]
