# Generated by Django 5.2.4 on 2025-07-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0034_remove_courseresource_r_name_courseresource_r_des_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseresource",
            name="r_num",
            field=models.CharField(max_length=20, verbose_name="资源序号"),
        ),
    ]
