# Generated by Django 5.2.4 on 2025-08-08 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0035_alter_courseresource_r_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="teachers.teacher",
                verbose_name="教师",
            ),
        ),
        migrations.AddField(
            model_name="courseresource",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homeworks",
                to="teachers.course",
                verbose_name="课程",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="t_num",
            field=models.CharField(
                editable=False, max_length=20, null=True, verbose_name="教师工号"
            ),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="l_num",
            field=models.CharField(
                editable=False, max_length=20, null=True, verbose_name="课程号"
            ),
        ),
    ]
