# Generated by Django 5.2.4 on 2025-08-08 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0037_alter_course_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="teachers.teacher",
                verbose_name="教师",
            ),
        ),
    ]
