# Generated by Django 5.2.4 on 2025-08-10 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0038_alter_course_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homeworks",
                to="teachers.course",
                verbose_name="关联课程",
            ),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="teachers.course",
                verbose_name="课程",
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="l_num",
            field=models.CharField(
                editable=False, max_length=20, null=True, verbose_name="课程号"
            ),
        ),
    ]
