# Generated by Django 5.2.4 on 2025-07-07 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Book",
            new_name="goods",
        ),
    ]
