# Generated by Django 5.2.4 on 2025-07-07 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_rename_book_goods"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="goods",
            new_name="books",
        ),
    ]
