# Generated by Django 5.2.4 on 2025-07-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0003_rename_goods_books"),
    ]

    operations = [
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("age", models.IntegerField()),
                ("username", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("snum", models.CharField(max_length=20)),
                ("sex", models.CharField(max_length=5)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("rdate", models.DateField()),
                ("lastlogin", models.DateTimeField()),
                ("is_available", models.BooleanField()),
                ("level", models.IntegerField()),
            ],
        ),
    ]
