# Generated by Django 5.2.4 on 2025-07-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0004_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="rdate",
            field=models.DateField(auto_now_add=True),
        ),
    ]
