# Generated by Django 5.2.4 on 2025-07-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0005_alter_student_rdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="is_available",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="lastlogin",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="level",
            field=models.IntegerField(null=True),
        ),
    ]
