# Generated by Django 5.2.4 on 2025-07-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0006_alter_student_age_alter_student_is_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="sex",
            field=models.IntegerField(
                choices=[(1, "男"), (2, "女")], null=True, verbose_name="性别"
            ),
        ),
    ]
