# Generated by Django 5.2.4 on 2025-07-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0007_alter_student_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="level",
            field=models.IntegerField(
                choices=[(1, "初学"), (2, "进阶")], default=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="sex",
            field=models.CharField(max_length=5),
        ),
    ]
