# Generated by Django 5.2.4 on 2025-07-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0008_alter_student_level_alter_student_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="sex",
            field=models.CharField(max_length=10),
        ),
    ]
