# Generated by Django 5.2.4 on 2025-07-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0009_alter_student_sex"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="sex",
        ),
    ]
