# Generated by Django 5.2.4 on 2025-07-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0010_remove_student_sex"),
    ]

    operations = []
