# Generated by Django 5.2.4 on 2025-07-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0011_auto_20250719_2109"),
    ]

    operations = []
