# Generated by Django 5.2.4 on 2025-07-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0012_auto_20250719_2117"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="sex",
            field=models.CharField(max_length=5, null=True),
        ),
    ]
