# Generated by Django 5.2.4 on 2025-07-21 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0013_student_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="jwt",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
