# Generated by Django 5.2.4 on 2025-07-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0014_student_is_active_student_jwt"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSubmission",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "u_num",
                    models.CharField(max_length=20, null=True, verbose_name="提交标号"),
                ),
                (
                    "s_num",
                    models.CharField(max_length=20, null=True, verbose_name="学生学号"),
                ),
                (
                    "t_num",
                    models.CharField(max_length=20, null=True, verbose_name="题目标号"),
                ),
                ("up_time", models.DateTimeField(null=True, verbose_name="提交时间")),
                (
                    "score",
                    models.CharField(max_length=5, null=True, verbose_name="分数"),
                ),
                ("advice", models.TextField(null=True, verbose_name="修改建议")),
                (
                    "ressuggest",
                    models.TextField(null=True, verbose_name="资源推荐理由"),
                ),
                (
                    "knowledgegraph",
                    models.CharField(
                        max_length=64, null=True, verbose_name="知识图谱路径"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("未提交", "未提交"),
                            ("草稿", "草稿"),
                            ("已提交", "已提交"),
                        ],
                        default="未提交",
                        max_length=5,
                        verbose_name="提交状态",
                    ),
                ),
            ],
        ),
    ]
