# Generated by Django 5.2.4 on 2025-07-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0016_student_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="WritingTopic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("t_num", models.CharField(max_length=50, verbose_name="教师编号")),
                ("title", models.CharField(max_length=255, verbose_name="题目标题")),
                ("des", models.TextField(verbose_name="题目描述")),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("types", models.CharField(max_length=50, verbose_name="题目类型")),
                ("s_up", models.BooleanField(default=False, verbose_name="学生上传")),
                (
                    "doc_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="文档名称"
                    ),
                ),
                (
                    "d_path",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="文档路径"
                    ),
                ),
            ],
            options={
                "verbose_name": "写作题目",
                "verbose_name_plural": "写作题目",
            },
        ),
    ]
