# Generated by Django 5.2.4 on 2025-07-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0017_writingtopic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="writingtopic",
            name="d_path",
        ),
        migrations.RemoveField(
            model_name="writingtopic",
            name="doc_name",
        ),
        migrations.RemoveField(
            model_name="writingtopic",
            name="s_up",
        ),
        migrations.RemoveField(
            model_name="writingtopic",
            name="t_num",
        ),
    ]
