# Generated by Django 5.2.4 on 2025-07-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0018_remove_writingtopic_d_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsubmission",
            name="filename",
            field=models.CharField(max_length=255, null=True, verbose_name="文件名"),
        ),
        migrations.AddField(
            model_name="documentsubmission",
            name="path",
            field=models.CharField(max_length=512, null=True, verbose_name="文件路径"),
        ),
    ]
