# Generated by Django 5.2.4 on 2025-07-23 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0019_documentsubmission_filename_documentsubmission_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="user",
        ),
    ]
